// Builds the trusted lesson catalog that the quiz repository's ai-tutor function
// reads for music-* requests. Node only; the browser reads catalog-versions.mjs.
import { createHash } from 'node:crypto';
import { STAGES, LESSONS } from '../static/music/curriculum.mjs';
import { LESSON_DETAILS } from '../static/music/lesson-details.mjs';

// Stable JSON: object keys sorted, so a lesson's version changes only with its content.
export function canonical(value) {
    if (Array.isArray(value)) return `[${value.map(canonical).join(',')}]`;
    if (value && typeof value === 'object') return `{${Object.keys(value).sort().map(key => `${JSON.stringify(key)}:${canonical(value[key])}`).join(',')}}`;
    return JSON.stringify(value);
}
export const lessonVersion = entry => createHash('sha256').update(canonical(entry)).digest('hex').slice(0, 16);

// Quiz questions and their answers are left out: explanations and homework do not need
// them, and the tutor must not be able to leak an answer before the learner tries.
export function buildCatalog() {
    const lessons = LESSONS.map(lesson => {
        const detail = LESSON_DETAILS[lesson.id];
        if (!detail) throw new Error(`lesson ${lesson.id} has no details`);
        const entry = {
            id: lesson.id, stage: lesson.stage, stageTitle: STAGES[lesson.stage][0], title: lesson.title,
            points: lesson.points, task: lesson.task, objectives: detail.objectives, sections: detail.sections,
            example: detail.example, practice: detail.practice, check: detail.check
        };
        return { ...entry, version: lessonVersion(entry) };
    });
    return { format: 1, lessons };
}
export const catalogVersions = catalog => Object.fromEntries(catalog.lessons.map(l => [l.id, l.version]));
export const versionsModule = catalog => `// Generated by tools/export-music-catalog.mjs. Do not edit by hand.\nexport const MUSIC_CATALOG_VERSIONS = ${JSON.stringify(catalogVersions(catalog), null, 1)};\n`;
